// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RihalAssignment.Api.Models;

namespace RihalAssignment.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211209231023_IntialCreation")]
    partial class IntialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("RihalAssignment.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("class_name");

                    b.HasKey("Id");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grade 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grade 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grade 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grade 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grade 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2020, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grade 6"
                        });
                });

            modelBuilder.Entity("RihalAssignment.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2020, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2020, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Montserrat"
                        });
                });

            modelBuilder.Entity("RihalAssignment.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CountryId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 5,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Alvera Leannon"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            CountryId = 10,
                            CreatedDate = new DateTime(2020, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Vernon Ambrose Douglas"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 4,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Carmel Denesik"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 5,
                            CountryId = 10,
                            CreatedDate = new DateTime(2020, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holly Osinski"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 4,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jasmin Kertzmann PhD"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 4,
                            CountryId = 2,
                            CreatedDate = new DateTime(2020, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Walker Lemuel Hessel"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 1,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mrs. Enrico Geo Goyette"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 2,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dashawn Bergnaum"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 2,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2014, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mrs. Anibal Roger Quitzon DVM"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 4,
                            CountryId = 1,
                            CreatedDate = new DateTime(2020, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Norwood Beatty"
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 2,
                            CountryId = 6,
                            CreatedDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dan Cummings"
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 2,
                            CountryId = 2,
                            CreatedDate = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rylan Jerde II"
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 1,
                            CountryId = 5,
                            CreatedDate = new DateTime(2021, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brice Grimes"
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 2,
                            CountryId = 5,
                            CreatedDate = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2006, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prof. Jabari Pierre Casper"
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 2,
                            CountryId = 4,
                            CreatedDate = new DateTime(2020, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hal Mayert"
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 2,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2006, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rosemary Grant"
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 6,
                            CountryId = 4,
                            CreatedDate = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sammie Dickinson"
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 3,
                            CountryId = 10,
                            CreatedDate = new DateTime(2020, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paxton Hand Jr."
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 6,
                            CountryId = 9,
                            CreatedDate = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Itzel Monahan II"
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 2,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hadley Rodriguez"
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 1,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Ottilie Orn DDS"
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 3,
                            CountryId = 6,
                            CreatedDate = new DateTime(2020, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Maureen Dolly Halvorson"
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 1,
                            CountryId = 7,
                            CreatedDate = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmed Swaniawski"
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 5,
                            CountryId = 8,
                            CreatedDate = new DateTime(2020, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nelle O'Connell"
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 5,
                            CountryId = 7,
                            CreatedDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Telly Wilkinson"
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 2,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garth Oscar Jenkins DDS"
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 1,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2014, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rita Prohaska II"
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 6,
                            CountryId = 7,
                            CreatedDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Darby Magdalena Lakin IV"
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 2,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Richmond Durgan"
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 1,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Marielle Peyton Shields DVM"
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 5,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lavada Rohan"
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 4,
                            CountryId = 2,
                            CreatedDate = new DateTime(2021, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Linwood Reinger"
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 1,
                            CountryId = 4,
                            CreatedDate = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenny Schuppe"
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 5,
                            CountryId = 1,
                            CreatedDate = new DateTime(2020, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ms. Harmony Mallory Hickle"
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 4,
                            CountryId = 6,
                            CreatedDate = new DateTime(2021, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chaya Kassulke"
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 1,
                            CountryId = 9,
                            CreatedDate = new DateTime(2021, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kyla Hauck"
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 5,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adeline Swaniawski V"
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 1,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wiley Erin Braun IV"
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 5,
                            CountryId = 4,
                            CreatedDate = new DateTime(2021, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2014, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Emmett Pinkie Mosciski"
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 3,
                            CountryId = 9,
                            CreatedDate = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dillan Gorczany"
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 1,
                            CountryId = 1,
                            CreatedDate = new DateTime(2020, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jon Williamson"
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 3,
                            CountryId = 2,
                            CreatedDate = new DateTime(2020, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Trudie Johnston"
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 1,
                            CountryId = 4,
                            CreatedDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ms. Ally Delilah Kovacek"
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 4,
                            CountryId = 7,
                            CreatedDate = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jordy Batz"
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 5,
                            CountryId = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2014, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maida Shields"
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 1,
                            CountryId = 5,
                            CreatedDate = new DateTime(2021, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lillie Jaskolski"
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 1,
                            CountryId = 9,
                            CreatedDate = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Javonte Zemlak"
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 1,
                            CountryId = 3,
                            CreatedDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Krystal Heath Satterfield"
                        },
                        new
                        {
                            Id = 49,
                            ClassId = 2,
                            CountryId = 2,
                            CreatedDate = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2013, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gabriella Effertz"
                        },
                        new
                        {
                            Id = 50,
                            ClassId = 6,
                            CountryId = 6,
                            CreatedDate = new DateTime(2021, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2009, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Martina Kristy Gislason II"
                        },
                        new
                        {
                            Id = 51,
                            ClassId = 3,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chaim Christiansen"
                        },
                        new
                        {
                            Id = 52,
                            ClassId = 6,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arvel VonRueden"
                        },
                        new
                        {
                            Id = 53,
                            ClassId = 2,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prof. Cesar Judd Mosciski V"
                        },
                        new
                        {
                            Id = 54,
                            ClassId = 1,
                            CountryId = 7,
                            CreatedDate = new DateTime(2021, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2006, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Javon Schuster"
                        },
                        new
                        {
                            Id = 55,
                            ClassId = 3,
                            CountryId = 10,
                            CreatedDate = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mrs. Ima Oliver Abernathy"
                        },
                        new
                        {
                            Id = 56,
                            ClassId = 6,
                            CountryId = 7,
                            CreatedDate = new DateTime(2021, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shanelle Elvera Pacocha Sr."
                        },
                        new
                        {
                            Id = 57,
                            ClassId = 3,
                            CountryId = 7,
                            CreatedDate = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Rebeca Russel"
                        },
                        new
                        {
                            Id = 58,
                            ClassId = 5,
                            CountryId = 2,
                            CreatedDate = new DateTime(2020, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ms. Elda Ethyl Ullrich I"
                        },
                        new
                        {
                            Id = 59,
                            ClassId = 5,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2009, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ms. Ophelia Bernhard"
                        },
                        new
                        {
                            Id = 60,
                            ClassId = 1,
                            CountryId = 8,
                            CreatedDate = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jermain Quitzon"
                        },
                        new
                        {
                            Id = 61,
                            ClassId = 1,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kassandra Larkin"
                        },
                        new
                        {
                            Id = 62,
                            ClassId = 6,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nathanael Terrell Kerluke I"
                        },
                        new
                        {
                            Id = 63,
                            ClassId = 6,
                            CountryId = 2,
                            CreatedDate = new DateTime(2021, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corene Jacobs"
                        },
                        new
                        {
                            Id = 64,
                            ClassId = 3,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Broderick Klein"
                        },
                        new
                        {
                            Id = 65,
                            ClassId = 6,
                            CountryId = 9,
                            CreatedDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Sylvan Gilbert Baumbach MD"
                        },
                        new
                        {
                            Id = 66,
                            ClassId = 6,
                            CountryId = 4,
                            CreatedDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mrs. Marcos Block"
                        },
                        new
                        {
                            Id = 67,
                            ClassId = 2,
                            CountryId = 4,
                            CreatedDate = new DateTime(2021, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2004, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hilma Fadel"
                        },
                        new
                        {
                            Id = 68,
                            ClassId = 2,
                            CountryId = 8,
                            CreatedDate = new DateTime(2020, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2009, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Izabella Feest"
                        },
                        new
                        {
                            Id = 69,
                            ClassId = 5,
                            CountryId = 10,
                            CreatedDate = new DateTime(2020, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jovanny Jude Rempel DVM"
                        },
                        new
                        {
                            Id = 70,
                            ClassId = 1,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2006, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jaida Kilback"
                        },
                        new
                        {
                            Id = 71,
                            ClassId = 4,
                            CountryId = 6,
                            CreatedDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Chasity Henry Bode"
                        },
                        new
                        {
                            Id = 72,
                            ClassId = 5,
                            CountryId = 8,
                            CreatedDate = new DateTime(2020, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2009, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Osvaldo Frankie Kreiger Sr."
                        },
                        new
                        {
                            Id = 73,
                            ClassId = 1,
                            CountryId = 9,
                            CreatedDate = new DateTime(2021, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2013, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Kobe Anastasia Hoppe IV"
                        },
                        new
                        {
                            Id = 74,
                            ClassId = 1,
                            CountryId = 8,
                            CreatedDate = new DateTime(2020, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toy Ritchie"
                        },
                        new
                        {
                            Id = 75,
                            ClassId = 3,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kacey Quigley"
                        },
                        new
                        {
                            Id = 76,
                            ClassId = 5,
                            CountryId = 2,
                            CreatedDate = new DateTime(2020, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Noemi Cole"
                        },
                        new
                        {
                            Id = 77,
                            ClassId = 1,
                            CountryId = 6,
                            CreatedDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lauryn Astrid Wintheiser Jr."
                        },
                        new
                        {
                            Id = 78,
                            ClassId = 4,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Roberto Wiegand"
                        },
                        new
                        {
                            Id = 79,
                            ClassId = 3,
                            CountryId = 9,
                            CreatedDate = new DateTime(2021, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2009, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Erna Hills"
                        },
                        new
                        {
                            Id = 80,
                            ClassId = 6,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Johann Tomas Hane Jr."
                        },
                        new
                        {
                            Id = 81,
                            ClassId = 6,
                            CountryId = 9,
                            CreatedDate = new DateTime(2021, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Abdullah Rolfson"
                        },
                        new
                        {
                            Id = 82,
                            ClassId = 1,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audie Johnson"
                        },
                        new
                        {
                            Id = 83,
                            ClassId = 4,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scarlett Monahan"
                        },
                        new
                        {
                            Id = 84,
                            ClassId = 5,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orie Bartell"
                        },
                        new
                        {
                            Id = 85,
                            ClassId = 5,
                            CountryId = 3,
                            CreatedDate = new DateTime(2020, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prof. Lawson Hackett"
                        },
                        new
                        {
                            Id = 86,
                            ClassId = 4,
                            CountryId = 9,
                            CreatedDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hector Fisher"
                        },
                        new
                        {
                            Id = 87,
                            ClassId = 3,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2015, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mrs. Eloisa Alek Hansen"
                        },
                        new
                        {
                            Id = 88,
                            ClassId = 3,
                            CountryId = 5,
                            CreatedDate = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2012, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mr. Susana Mayert II"
                        },
                        new
                        {
                            Id = 89,
                            ClassId = 2,
                            CountryId = 5,
                            CreatedDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2004, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Priscilla Pollich"
                        },
                        new
                        {
                            Id = 90,
                            ClassId = 3,
                            CountryId = 10,
                            CreatedDate = new DateTime(2021, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2010, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marina Bartell"
                        },
                        new
                        {
                            Id = 91,
                            ClassId = 1,
                            CountryId = 3,
                            CreatedDate = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmed Emelie Heaney DDS"
                        },
                        new
                        {
                            Id = 92,
                            ClassId = 4,
                            CountryId = 3,
                            CreatedDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prof. Lloyd Kozey II"
                        },
                        new
                        {
                            Id = 93,
                            ClassId = 1,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kaylin Krajcik"
                        },
                        new
                        {
                            Id = 94,
                            ClassId = 1,
                            CountryId = 9,
                            CreatedDate = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2008, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenora Lubowitz"
                        },
                        new
                        {
                            Id = 95,
                            ClassId = 1,
                            CountryId = 9,
                            CreatedDate = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2007, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dayana Jacobs"
                        },
                        new
                        {
                            Id = 96,
                            ClassId = 4,
                            CountryId = 1,
                            CreatedDate = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jannie Pouros"
                        },
                        new
                        {
                            Id = 97,
                            ClassId = 1,
                            CountryId = 7,
                            CreatedDate = new DateTime(2020, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2011, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miss Nat Alexys McGlynn"
                        },
                        new
                        {
                            Id = 98,
                            ClassId = 2,
                            CountryId = 8,
                            CreatedDate = new DateTime(2021, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2013, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2020, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Giles Dickens"
                        },
                        new
                        {
                            Id = 99,
                            ClassId = 2,
                            CountryId = 8,
                            CreatedDate = new DateTime(2020, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2004, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prof. Alfreda Hickle IV"
                        },
                        new
                        {
                            Id = 100,
                            ClassId = 5,
                            CountryId = 7,
                            CreatedDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2021, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karolann Cruickshank"
                        });
                });

            modelBuilder.Entity("RihalAssignment.Models.Student", b =>
                {
                    b.HasOne("RihalAssignment.Models.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RihalAssignment.Models.Country", "Countries")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
